pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:checkstore/waaw.git
          - cd waaw.git
          - git push --mirror git@github.com:LojaWaaw/waaw-checkstore.git